name: cryptography_plus
version: 2.7.1
homepage: https://github.com/emz-hanauer/dart-cryptography
description:
  Cryptographic algorithms for encryption, digital signatures, key agreement, authentication, and
  hashing. AES, Chacha20, ED25519, X25519, Argon2, and more. Good cross-platform support.
topics:
  - crypto

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  #
  # Packages by Google:
  #
  collection: ^1.17.0
  crypto: ^3.0.3
  ffi: ^2.1.0
  js: ^0.7.1
  meta: ^1.8.0
  typed_data: ^1.3.0

dev_dependencies:
  #
  # Packages by Google:
  #
  lints: ^2.1.1
  test: ^1.24.0
